apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo
  namespace: bluegreen-demo
  labels:
    kargo.akuity.io/cred-type: git
type: Opaque
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
