apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    color: green
  name: nginx-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: green
  template:
    metadata:
      labels:
        app: nginx
        color: green
    spec:
      containers:
      - image: public.ecr.aws/nginx/nginx:1.31.5
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /usr/share/nginx/html/index.html
          name: page
          subPath: index.html
      volumes:
      - configMap:
          name: nginx-page-green-m6fmgff2gt
        name: page
