apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: bluegreen
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - overlay: blue
            stage: preview
          - overlay: green
            stage: preview
          - overlay: preview
            stage: preview
          - overlay: live
            stage: live
  template:
    metadata:
      name: bluegreen-{{ .overlay }}
      annotations:
        kargo.akuity.io/authorized-stage: bluegreen-demo:{{ .stage }}
    spec:
      project: default
      source:
        repoURL: ${GITOPS_REPO_URL}
        targetRevision: main
        path: env/overlays/{{ .overlay }}
      destination:
        name: ${ARGOCD_DESTINATION}
        namespace: bluegreen
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
