apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-blue
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: bluegreen-demo:preview
spec:
  project: default
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: main
    path: env/overlays/blue
  destination:
    name: ${ARGOCD_DESTINATION}
    namespace: bluegreen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-green
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: bluegreen-demo:preview
spec:
  project: default
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: main
    path: env/overlays/green
  destination:
    name: ${ARGOCD_DESTINATION}
    namespace: bluegreen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bluegreen-live
  namespace: argocd
  annotations:
    kargo.akuity.io/authorized-stage: bluegreen-demo:live
spec:
  project: default
  source:
    repoURL: ${GITOPS_REPO_URL}
    targetRevision: main
    path: env/overlays/live
  destination:
    name: ${ARGOCD_DESTINATION}
    namespace: bluegreen
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
